# litert/samples/blazeface_app/BUILD

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "blazeface_app",
    srcs = ["main.cc"],
    deps = [
        "//litert/cc:litert_api_with_dynamic_runtime",
        # You will need to add a dependency for an image loading library.
        # For example, if you use OpenCV, you would add its Bazel target here.
    ],
)
